spring:
    application:
        name: product


    datasource:
        url: jdbc:postgresql://localhost:5433/buildingStore
        username: user
        password: 123

    sql:
        init:
            schema-locations: classpath:/database/schema.sql
            mode: always



server:
    port: 8091